- name: Gather Hardware Information
  hosts: all
  gather_facts: yes

  tasks:
    - name: Set Hardware Facts Variable
      set_fact:
        hardware_specs: "{{ ansible_facts }}"

    - name: Save Hardware Information to YAML
      copy:
        content: "{{ hardware_specs | to_yaml }}"
        dest: "Destination to path"
      delegate_to: localhost

